// BODA shared data model for fortune-service discovery pages.
// Purpose of each array:
// - SERVICES: normalized service catalog entries for list/detail/filtering UI.
// - CONSULTATION_TYPES: major consultation topics users search for.
// - SERVICE_TYPES: platform/business model group labels for services.
// - METHODS: consultation delivery methods used by filters and badges.
// - PRICE_RANGES: numeric buckets used for price filters and summaries.
// - REVIEWS: AI-aggregated public review digests per service.
// - ARTICLES: editorial metadata for content/recommendation modules.

/**
 * @typedef {'positive' | 'negative' | 'neutral' | null} Sentiment
 */

/**
 * @typedef {{
 *   name: string,
 *   url: string,
 *   reviewCount: number | null
 * }} ReviewSource
 */

/**
 * @typedef {{
 *   aiSummary: string | null,
 *   sentiment: Sentiment,
 *   keywords: string[],
 *   pros: string[],
 *   cons: string[],
 *   sourceCount: number,
 *   lastUpdated: string | null,
 *   sources: ReviewSource[]
 * }} ServiceReviewSummary
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   type: string,
 *   method: string[],
 *   specialty: string[],
 *   counselingType: string[],
 *   priceRange: string,
 *   priceStructure: '건당정액' | '분당과금' | '월구독' | '무료' | '무료+부분유료',
 *   extraCharges: boolean,
 *   freeTrial: string | null,
 *   platform: string[],
 *   counselorCount: number | '다수' | null,
 *   signupRequired: boolean,
 *   reviewCount: number | null,
 *   operatingHours: string,
 *   summary: string,
 *   officialUrl: string,
 *   rating: number | null,
 *   reviewSummary: ServiceReviewSummary
 * }} Service
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   keywords: string[]
 * }} ConsultationType
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   icon: string
 * }} ServiceType
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   desc: string
 * }} Method
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   min?: number,
 *   max?: number
 * }} PriceRange
 */

/**
 * @typedef {{
 *   id: string,
 *   serviceId: string,
 *   period: string,
 *   aiSummary: string | null,
 *   sentiment: Sentiment,
 *   keywords: string[],
 *   pros: string[],
 *   cons: string[],
 *   sourceCount: number,
 *   lastUpdated: string | null,
 *   sources: ReviewSource[]
 * }} ReviewDigest
 */

/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   category: string,
 *   slug: string,
 *   publishedAt: string,
 *   summary: string,
 *   tags: string[]
 * }} Article
 */

/**
 * @typedef {{
 *   name: string,
 *   nameEn: string,
 *   tagline: string,
 *   email: string,
 *   domain: string,
 *   url: string,
 *   disclaimer: string
 * }} Brand
 */

/** @type {Service[]} */
const SERVICES = [
  // ── 전화상담플랫폼 (7) ─────────────────────────────────────────
  {
    id: 'sajochungung',
    name: '사주천궁',
    type: '전화상담플랫폼',
    method: ['전화 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '진로/취업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: 500,
    signupRequired: true,
    reviewCount: 1310000,
    operatingHours: '24시간',
    summary: '리얼후기 131만 건, 상담사 500여 명 규모의 국내 최대 전화상담 플랫폼',
    officialUrl: 'http://46saju.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'chunmyung',
    name: '천명',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담', '대면 상담'],
    specialty: ['연애/궁합', '진로/취업', '재물/사업', '건강', '종합운', '가족/관계'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 400000,
    operatingHours: '24시간',
    summary: '후기 40만 건 이상, 엄격한 입점 심사로 신뢰성을 강조하는 대표 전화상담 플랫폼',
    officialUrl: 'https://chunmyung.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'ssintong',
    name: '신통',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '진로/취업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: 'MZ세대 타깃 고화질 영상 상담 도입, 2025년 최대 신흥 전화상담 플랫폼',
    officialUrl: 'https://ssintong.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'soultalk',
    name: '소울톡',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['타로', '사주', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 530000,
    operatingHours: '24시간',
    summary: '타로마스터 정회도(유튜브 54만) 공식 추천, 누적 상담 53만 건의 타로 특화 플랫폼',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'sajoonaru',
    name: '사주나루',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '코인 선불·후불 선택 가능, 30초당 1,100~1,500원 분당 과금 방식의 전화상담 플랫폼',
    officialUrl: 'https://sajunaru.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'unse7',
    name: '운세7',
    type: '전화상담플랫폼',
    method: ['전화 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '신점·타로·사주 전문 상담사를 갖춘 분당 과금 방식 전화상담 플랫폼',
    officialUrl: 'https://www.unse7.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'unsedamda',
    name: '운세담다',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1만원 이하',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: 0,
    operatingHours: null,
    summary: '저렴한 비용을 강조하는 전화·채팅 상담 플랫폼',
    officialUrl: 'https://www.unsedamda.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },

  // ── 앱기반자동풀이 (11) ────────────────────────────────────────
  {
    id: 'jeomsin',
    name: '점신',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '건강', '진로/취업', '가족/관계'],
    counselingType: ['사주', '타로', '관상', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: 996000,
    operatingHours: '24시간',
    summary: '누적 다운로드 1,700만, MAU 95만의 국내 1위 운세 앱. 관상·심리테스트 등 다양한 콘텐츠 제공',
    officialUrl: 'https://www.jeomsin.co.kr',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'postellar',
    name: '포스텔러',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '점성술', '별자리'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '누적 가입자 900만, 연 매출 100억 원 이상의 MZ세대 대표 운세 앱. 사주·타로·점성술 통합',
    officialUrl: 'https://postellar.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'unsebigul',
    name: '운세비결',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운'],
    counselingType: ['토정비결', '사주', '오늘의 운세'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '토정비결·신년운세 중심의 운세 앱, 사용 편리성 호평',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'ujucat-bora',
    name: '우주고양이 보라',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: 'iOS 운세 앱 평점 1위(4.8점), KAIST 연구진과 유명 사주가 4인이 협업한 MZ 연애운 특화 앱',
    officialUrl: null,
    rating: 4.8,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'ozstarot',
    name: '오즈의타로',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '투시타로로 인기를 얻은 타로 전문 앱, 인터페이스와 배경음악 호평',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'jeongtong-saju',
    name: '정통사주',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업', '건강', '진로/취업'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '건당정액',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '50가지 이상 정통 사주 콘텐츠를 제공하는 명리학 기반 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'inyeon',
    name: '인연궁합',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합'],
    counselingType: ['사주'],
    priceRange: '1~3만원',
    priceStructure: '건당정액',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '궁합 전문 앱, 한 번 결제(22,000원~)로 여러 생년월일 비교 가능',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'hwangje-unse',
    name: '황제운세',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '토정비결', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '무료 운세·사주·궁합·토정비결·꿈해몽을 제공하는 종합 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'mytarot',
    name: '마이타로',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이', 'AI 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['타로', '사주', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '정통 명리학 사주풀이와 AI 기반 타로 리딩을 결합한 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'unsudowon',
    name: '운수도원 투데이',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '오늘의 운세'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '궁합·연애스타일 분석에 호평을 받는 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'unsebichaek',
    name: '운세비책',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '신년운세·사주·궁합 풀이를 제공하는 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },

  // ── AI운세 (6) ─────────────────────────────────────────────────
  {
    id: 'hellobot',
    name: '헬로우봇',
    type: 'AI운세',
    method: ['앱 자동 풀이', 'AI 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '누적 다운로드 100만+, AI 챗봇 기반 타로·사주·별자리·손금 통합 상담 앱',
    officialUrl: 'https://hellobot.co',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'hori-ai',
    name: '호리AI',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '점성술'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '사주·타로·점성술·자미두수 등을 AI가 직접 계산·해석하는 무료 베타 서비스',
    officialUrl: 'https://hori.chat',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'dosa-ai',
    name: '도사',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['종합운', '연애/궁합', '재물/사업', '진로/취업'],
    counselingType: ['사주', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '천문 데이터 기반 정밀 사주 계산과 24시간 AI 상담을 제공하는 AI 사주 플랫폼',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'annyeong-tarot',
    name: '안녕타로',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['타로'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: 'AI 타로 마스터와 대화하며 고민을 해결하는 AI 타로 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'unsewiki',
    name: '운세위키',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '진로/취업'],
    counselingType: ['사주'],
    priceRange: '1만원 이하',
    priceStructure: '건당정액',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 27227,
    operatingHours: '24시간',
    summary: '1982년 정통 사주명리 기반 AI 분석, 누적 20만+ 이용자. 토스 파트너사, 동아일보 브랜드 대상 수상',
    officialUrl: 'https://luckyloveme.com',
    rating: 4.8,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },
  {
    id: 'zendi',
    name: '젠디',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: 'App Store 평점 4.9, 현대적 감각으로 사주를 재해석하는 AI 채팅 운세 앱',
    officialUrl: null,
    rating: 4.9,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
  },

  // ── 포털무료운세 (3) ───────────────────────────────────────────
  {
    id: 'naver-unse',
    name: '네이버 운세',
    type: '포털무료운세',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '오늘의 운세', '토정비결', '별자리'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹', '앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '접근성 최고의 포털 무료 운세, 간결한 해석 제공',
    officialUrl: 'https://search.naver.com/search.naver?query=운세',
    rating: null,
    reviewSummary: {
      aiSummary: '포털 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '포털'],
      pros: ['접근성 높음'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
  },
  {
    id: 'nate-unse',
    name: '네이트 운세',
    type: '포털무료운세',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '무료 기본 운세와 다양한 유료 프리미엄 콘텐츠를 제공하는 포털 운세',
    officialUrl: 'https://m.fortune.nate.com',
    rating: null,
    reviewSummary: {
      aiSummary: '포털 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '포털'],
      pros: ['기본 운세 무료 제공'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
  },
  {
    id: 'fortuneaid',
    name: '포춘에이드',
    type: '포털무료운세',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '타로', '점성술', '별자리', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '동서양 운세를 폭넓게 다루는 무료 운세 포털',
    officialUrl: 'https://www.fortunade.com',
    rating: null,
    reviewSummary: {
      aiSummary: '포털 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '포털'],
      pros: ['콘텐츠 폭이 넓음'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
  },

  // ── 기업제공무료 (3) ───────────────────────────────────────────
  {
    id: 'shinhan-unse',
    name: '신한라이프 운세',
    type: '기업제공무료',
    method: ['앱 자동 풀이'],
    specialty: ['종합운'],
    counselingType: ['사주', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '평생운세 풀이에 호평을 받는 신한라이프 무료 운세 서비스',
    officialUrl: 'https://www.shinhanlife.co.kr',
    rating: null,
    reviewSummary: {
      aiSummary: '기업 제공 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '기업제공'],
      pros: ['무료 제공'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
  },
  {
    id: 'nonghyup-unse',
    name: '농협 운세',
    type: '기업제공무료',
    method: ['앱 자동 풀이'],
    specialty: ['종합운'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '100% 무료, 이용자 호평이 많은 농협 제공 운세 서비스 (PC 전용)',
    officialUrl: 'https://www.nonghyup.com',
    rating: null,
    reviewSummary: {
      aiSummary: '기업 제공 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '기업제공'],
      pros: ['완전 무료'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
  },
  {
    id: 'asiae-unse',
    name: '아시아경제 운세',
    type: '기업제공무료',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '오늘의 운세', '토정비결', '궁합'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '아시아경제 천기누설 브랜드, 정통사주·궁합·토정비결·이름풀이를 제공하는 언론사 무료 운세',
    officialUrl: 'https://www.asiae.co.kr/fortune/index.htm',
    rating: null,
    reviewSummary: {
      aiSummary: '언론사 제공 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '언론사'],
      pros: ['전통 사주·궁합 콘텐츠 풍부'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
  },
];

/** @type {ConsultationType[]} */
const CONSULTATION_TYPES = [
  { id: 'love', name: '연애/궁합', keywords: ['연애운', '궁합', '속마음', '재회', '결혼', '썸'] },
  { id: 'career', name: '진로/취업', keywords: ['이직', '취업', '적성', '직업운'] },
  { id: 'wealth', name: '재물/사업', keywords: ['재물운', '사업운', '투자', '금전'] },
  { id: 'health', name: '건강', keywords: ['건강운', '질병'] },
  { id: 'general', name: '종합운', keywords: ['신년운세', '토정비결', '평생운', '인생총운'] },
  { id: 'family', name: '가족/관계', keywords: ['부모', '자녀', '직장 인간관계'] },
];

/** @type {ServiceType[]} */
const SERVICE_TYPES = [
  { id: 'phone', name: '전화상담플랫폼', icon: '📞' },
  { id: 'app', name: '앱기반자동풀이', icon: '📱' },
  { id: 'ai', name: 'AI운세', icon: '🤖' },
  { id: 'portal', name: '포털무료운세', icon: '🌐' },
  { id: 'corporate', name: '기업제공무료', icon: '🏢' },
  { id: 'offline', name: '오프라인점집', icon: '🏠' },
  { id: 'tarotcafe', name: '타로카페', icon: '☕' },
];

/** @type {Method[]} */
const METHODS = [
  { id: 'phone', name: '전화 상담', desc: '실시간 음성, 즉각 피드백' },
  { id: 'chat', name: '채팅 상담', desc: '텍스트 기반, 기록 남음' },
  { id: 'visit', name: '대면 상담', desc: '직접 방문, 현장감' },
  { id: 'auto', name: '앱 자동 풀이', desc: '즉시 결과, 저렴/무료' },
  { id: 'ai', name: 'AI 상담', desc: '24시간, 무료~저가' },
];

/** @type {PriceRange[]} */
const PRICE_RANGES = [
  { id: 'free', name: '무료', max: 0 },
  { id: 'under10k', name: '1만원 이하', max: 10000 },
  { id: '10k-30k', name: '1~3만원', min: 10000, max: 30000 },
  { id: '30k-50k', name: '3~5만원', min: 30000, max: 50000 },
  { id: 'over50k', name: '5만원 이상', min: 50000 },
];

/** @type {ReviewDigest[]} */
const REVIEWS = [
  {
    id: 'chunmyung-2026q1',
    serviceId: 'chunmyung',
    period: '2026-Q1',
    aiSummary: '응답 속도와 상담사 친절도에 대한 만족 의견이 많지만, 시간 경과에 따른 비용 체감은 엇갈립니다.',
    sentiment: 'positive',
    keywords: ['친절', '빠른연결', '가격부담'],
    pros: ['상담사 선택 폭이 넓음', '야간에도 연결 가능'],
    cons: ['장시간 상담 시 요금 부담', '상담사 편차 존재'],
    sourceCount: 3,
    lastUpdated: '2026-03-02',
    sources: [
      { name: 'Google Play Store', url: 'https://play.google.com', reviewCount: null },
      { name: 'App Store', url: 'https://www.apple.com/app-store', reviewCount: null },
      { name: '공식 앱 후기', url: 'https://example.com/chunmyung/reviews', reviewCount: 1200 },
    ],
  },
  {
    id: 'saju-onair-2026q1',
    serviceId: 'saju-onair',
    period: '2026-Q1',
    aiSummary: '가볍게 확인하는 일일 운세 용도로 만족도가 높고, 심층 해석의 깊이는 보완 요구가 있습니다.',
    sentiment: 'neutral',
    keywords: ['간편함', '일일운세', '해석깊이'],
    pros: ['회원가입 없이 시작 가능', '결과 확인 속도가 빠름'],
    cons: ['심층 상담 대체는 어려움', '유료 리포트 가격 체감 차이'],
    sourceCount: 2,
    lastUpdated: '2026-03-02',
    sources: [
      { name: 'Google Play Store', url: 'https://play.google.com', reviewCount: null },
      { name: '공식 웹 리뷰', url: 'https://example.com/saju-onair/reviews', reviewCount: 430 },
    ],
  },
];

/** @type {Article[]} */
const ARTICLES = [
  {
    id: 'phone-taro-top5',
    title: '전화 타로 플랫폼 5곳 비교 - 가격·후기·특징 정리',
    category: '비교분석',
    slug: 'phone-taro-top5',
    publishedAt: '2026-03-02',
    summary: '대표 전화 타로 플랫폼 5곳의 가격 구조와 후기 경향을 한 페이지에서 비교합니다.',
    tags: ['전화타로', '가격비교', '후기요약'],
  },
  {
    id: 'saju-vs-taro-vs-sinjeom',
    title: '사주 vs 타로 vs 신점, 나에게 맞는 운세는?',
    category: '초보자가이드',
    slug: 'saju-vs-taro-vs-sinjeom',
    publishedAt: '2026-03-02',
    summary: '처음 운세를 보는 사람을 위해 상담 종류별 특징과 선택 기준을 정리했습니다.',
    tags: ['사주', '타로', '신점'],
  },
  {
    id: 'fortune-price-guide',
    title: '운세 상담, 얼마를 써야 적당할까? 가격 총정리',
    category: '가격가이드',
    slug: 'fortune-price-guide',
    publishedAt: '2026-03-02',
    summary: '무료부터 분당 과금까지, 운세 서비스 가격을 예산 구간별로 정리합니다.',
    tags: ['운세가격', '예산', '분당과금'],
  },
  {
    id: 'ai-fortune-review',
    title: 'AI 운세 서비스, 실제로 써보니 - 호리AI·아리사주 비교',
    category: '트렌드',
    slug: 'ai-fortune-review',
    publishedAt: '2026-03-02',
    summary: 'AI 운세 서비스의 장점과 한계를 사용 흐름 기준으로 비교 분석합니다.',
    tags: ['AI운세', '호리AI', '아리사주'],
  },
  {
    id: 'app-fortune-comparison',
    title: '점신 vs 포스텔러 vs 헬로우봇 - 운세 앱 3대장 비교',
    category: '비교분석',
    slug: 'app-fortune-comparison',
    publishedAt: '2026-03-02',
    summary: '국내 대표 운세 앱 3종의 콘텐츠 구성과 과금 구조를 비교합니다.',
    tags: ['점신', '포스텔러', '헬로우봇'],
  },
];

/** @type {Brand} */
const BRAND = {
  name: '보다',
  nameEn: 'BODA',
  tagline: '운세를 보다, 더 보다 나은 선택',
  email: 'hello@unsetok.com',
  domain: 'unsetok.com',
  url: 'https://unsetok.com',
  disclaimer:
    'BODA는 운세 서비스의 정보를 비교·제공하는 플랫폼이며, 특정 서비스의 효과나 정확성을 보증하지 않습니다. 서비스 이용에 따른 결과는 이용자 본인의 판단과 책임 하에 이루어집니다. 운세 상담은 참고용이며, 중요한 의사결정은 전문가(의료/법률/재무 등)와 상의하시기 바랍니다.',
};

// Browser + Node.js compatibility.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SERVICES, CONSULTATION_TYPES, SERVICE_TYPES, METHODS, PRICE_RANGES, REVIEWS, ARTICLES, BRAND };
} else {
  window.BODA_DATA = { SERVICES, CONSULTATION_TYPES, SERVICE_TYPES, METHODS, PRICE_RANGES, REVIEWS, ARTICLES, BRAND };
}
