// BODA shared data model for fortune-service discovery pages.
// Purpose of each array:
// - SERVICES: normalized service catalog entries for list/detail/filtering UI.
// - CONSULTATION_TYPES: major consultation topics users search for.
// - SERVICE_TYPES: platform/business model group labels for services.
// - METHODS: consultation delivery methods used by filters and badges.
// - PRICE_RANGES: numeric buckets used for price filters and summaries.
// - REVIEWS: AI-aggregated public review digests per service.
// - ARTICLES: editorial metadata for content/recommendation modules.

/**
 * @typedef {'positive' | 'negative' | 'neutral' | null} Sentiment
 */

/**
 * @typedef {{
 *   name: string,
 *   url: string,
 *   reviewCount: number | null
 * }} ReviewSource
 */

/**
 * @typedef {{
 *   aiSummary: string | null,
 *   sentiment: Sentiment,
 *   keywords: string[],
 *   pros: string[],
 *   cons: string[],
 *   sourceCount: number,
 *   lastUpdated: string | null,
 *   sources: ReviewSource[]
 * }} ServiceReviewSummary
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   type: string,
 *   method: string[],
 *   specialty: string[],
 *   counselingType: string[],
 *   priceRange: string,
 *   priceStructure: '건당정액' | '분당과금' | '월구독' | '무료' | '무료+부분유료',
 *   extraCharges: boolean,
 *   freeTrial: string | null,
 *   platform: string[],
 *   counselorCount: number | '다수' | null,
 *   signupRequired: boolean,
 *   reviewCount: number | null,
 *   operatingHours: string,
 *   summary: string,
 *   officialUrl: string,
 *   rating: number | null,
 *   reviewSummary: ServiceReviewSummary,
 *   pricingDetail: { costPerUnit: string, avgCost15min: number, avgCost30min: number, costRange15min: number[], vatIncluded: boolean, billingType: string, realCostExample: string },
 *   consumerWarnings: { type: 'caution' | 'tip' | 'positive', text: string }[],
 *   situationMatch: string[]
 * }} Service
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   keywords: string[]
 * }} ConsultationType
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   icon: string
 * }} ServiceType
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   desc: string
 * }} Method
 */

/**
 * @typedef {{
 *   id: string,
 *   name: string,
 *   min?: number,
 *   max?: number
 * }} PriceRange
 */

/**
 * @typedef {{
 *   id: string,
 *   serviceId: string,
 *   period: string,
 *   aiSummary: string | null,
 *   sentiment: Sentiment,
 *   keywords: string[],
 *   pros: string[],
 *   cons: string[],
 *   sourceCount: number,
 *   lastUpdated: string | null,
 *   sources: ReviewSource[]
 * }} ReviewDigest
 */

/**
 * @typedef {{
 *   id: string,
 *   title: string,
 *   category: string,
 *   slug: string,
 *   publishedAt: string,
 *   summary: string,
 *   tags: string[]
 * }} Article
 */

/**
 * @typedef {{
 *   name: string,
 *   nameEn: string,
 *   tagline: string,
 *   email: string,
 *   domain: string,
 *   url: string,
 *   disclaimer: string
 * }} Brand
 */

/** @type {Service[]} */
const SERVICES = [
  // ── 전화상담플랫폼 (7) ─────────────────────────────────────────
  {
    id: 'sajochungung',
    name: '사주천궁',
    type: '전화상담플랫폼',
    method: ['전화 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '진로/취업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: 500,
    signupRequired: true,
    reviewCount: 1310000,
    operatingHours: '24시간',
    summary: '리얼후기 131만 건, 상담사 500여 명 규모의 국내 최대 전화상담 플랫폼',
    officialUrl: 'http://46saju.com',
    rating: null,
    reviewSummary: {
      aiSummary: '리얼후기 131만 건, 상담사 500여 명 규모의 국내 최대 전화상담 플랫폼입니다. 상담사 선택 폭이 넓고 24시간 연결 가능하다는 장점이 있으나, 분당 과금 방식으로 장시간 상담 시 비용 부담이 있을 수 있습니다.',
      sentiment: 'positive',
      keywords: ['타로', '무료', '정확', '운세'],
      pros: ['무료 재회 신점 완벽 가이드', '이별 후 1년간 각종 무료/유료 신점을 경험하고, 현재는 명리학을 공부하고 있는 30대 직장인입니다', '오늘은 제가 실제로 경험한 무료 재회 신점의 모든 것을 진솔하게 나누고자 합니다'],
      cons: ['- 장점: 부담 없는 접근성', '- 단점: 비용 부담', '2) 사기 사이트 구별법'],
      sourceCount: 2,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://caomeiyun3.tistory.com/197', reviewCount: 2 }]
    },
    pricingDetail: {
      costPerUnit: '30초당 1,200~1,700코인',
      avgCost15min: 46200,
      avgCost30min: 92400,
      costRange15min: [39600, 56100],
      vatIncluded: true,
      billingType: '분당과금',
      realCostExample: '코인 선불 1,200~1,600코인/30초, 인기 상담사 15분 ≈ 49,500원(VAT포함)'
    },
    consumerWarnings: [
      { type: 'caution', text: '자동충전 설정 시 코인 부족 시 자동 결제 발생' },
      { type: 'caution', text: '060 후불 이용 시 정보이용료+통신사 요금 이중 청구' },
      { type: 'tip', text: '코인 선불이 060 후불보다 최대 20% 저렴' }
    ],
    situationMatch: ['심야상담', '전문분석'],
  },
  {
    id: 'chunmyung',
    name: '천명',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담', '대면 상담'],
    specialty: ['연애/궁합', '진로/취업', '재물/사업', '건강', '종합운', '가족/관계'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 400000,
    operatingHours: '24시간',
    summary: '후기 40만 건 이상, 엄격한 입점 심사로 신뢰성을 강조하는 대표 전화상담 플랫폼',
    officialUrl: 'https://chunmyung.com',
    rating: null,
    reviewSummary: {
      aiSummary: '건당 고정가(3.5~5만원) 방식으로 시간 걱정 없이 상담받을 수 있다는 점이 큰 장점입니다. 엄격한 상담사 입점 심사로 신뢰성을 강조하며, 후기 40만 건 이상을 보유한 대표 전화상담 플랫폼입니다.',
      sentiment: 'positive',
      keywords: ['타로', '사주', '정확', 'AI', '궁합'],
      pros: ['이번에 후기를 남길 잠실 주리 선생님 사주 상담은 천명이라는 서비스를 이용하였습니다', '이번에 처음 써봤는데 생각보다 괜찮았습니다', '자세한 후기를 남기기 전에 결론부터 말씀드리자면 꽤나 만족스러운 사주 상담이었습니다'],
      cons: ['가격이 꽤나 부담되죠', '리뷰 원탑이니 가격이 부담되어도 믿고 가는 것으로 결정', '꽤나 부담되는 가격, 30분에 55,000원이니까요'],
      sourceCount: 8,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://trueteller.tistory.com/3', reviewCount: 8 }]
    },
    pricingDetail: {
      costPerUnit: '건당 35,000~50,000원',
      avgCost15min: 42500,
      avgCost30min: 42500,
      costRange15min: [35000, 50000],
      vatIncluded: true,
      billingType: '건당정액',
      realCostExample: '건당 고정가(35,000~50,000원), 추가과금 없음. 시간 무관.'
    },
    consumerWarnings: [
      { type: 'positive', text: '건당 고정가로 추가 과금 없음' },
      { type: 'caution', text: '1만원부터 마케팅이나 인기 상담사는 3.5~5만원' },
      { type: 'tip', text: '시간 걱정 없이 상담받고 싶다면 천명이 유리' }
    ],
    situationMatch: ['심야상담', '전문분석', '위로공감'],
  },
  {
    id: 'ssintong',
    name: '신통',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '진로/취업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: 'MZ세대 타깃 고화질 영상 상담 도입, 2025년 최대 신흥 전화상담 플랫폼',
    officialUrl: 'https://ssintong.com',
    rating: null,
    reviewSummary: {
      aiSummary: 'MZ세대를 타깃으로 고화질 영상 상담을 도입한 신흥 전화상담 플랫폼입니다. 2025년 출시 이후 빠르게 성장하고 있으며, 사주·타로·신점 전문 상담사를 갖추고 있습니다.',
      sentiment: 'positive',
      keywords: ['사주', '정확', '무료'],
      pros: ['그렇게 유니아 수녀는 과거 자신의 동료 수녀였으나 현재 무당인 \'효원\'(김국희 배우)에게 도움을 청해 희준을 구하기 위한 의식들을 시도해 보지만 이 방법 역시 신', '그러나 배우들의 연기가 전반적으로 좋았고 시각적 연출에 심혈을 기울인 듯하여 볼거리가 나름 많았던 부분은 긍정적으로 보였던 것 같아요', '함께 보면 좋은 글'],
      cons: ['그 부분이 조금 아쉬웠어요', '한국의 역사기록은 앞서도 언급하였듯이 약소국의', '사기」와「삼국유사」뿐이다'],
      sourceCount: 4,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://lucky-hee.tistory.com/251', reviewCount: 4 }]
    },
    pricingDetail: {
      costPerUnit: '30초당 1,000~1,500원(추정)',
      avgCost15min: 37500,
      avgCost30min: 75000,
      costRange15min: [33000, 49500],
      vatIncluded: true,
      billingType: '분당과금',
      realCostExample: 'MZ타겟 영상상담 플랫폼, 분당 과금 방식'
    },
    consumerWarnings: [{ type: 'tip', text: 'MZ세대 타겟 고화질 영상 상담 제공' }],
    situationMatch: ['심야상담', 'MZ감성'],
  },
  {
    id: 'soultalk',
    name: '소울톡',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['타로', '사주', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 530000,
    operatingHours: '24시간',
    summary: '타로마스터 정회도(유튜브 54만) 공식 추천, 누적 상담 53만 건의 타로 특화 플랫폼',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '30초당 1,000~1,500원(추정)',
      avgCost15min: 37500,
      avgCost30min: 75000,
      costRange15min: [33000, 49500],
      vatIncluded: true,
      billingType: '분당과금',
      realCostExample: '타로마스터 추천 플랫폼, 분당 과금'
    },
    consumerWarnings: [{ type: 'tip', text: '타로마스터 정회도(유튜브 54만) 공식 추천 플랫폼' }],
    situationMatch: ['심야상담', '위로공감', '연애특화'],
  },
  {
    id: 'sajoonaru',
    name: '사주나루',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '코인 선불·후불 선택 가능, 30초당 1,100~1,500원 분당 과금 방식의 전화상담 플랫폼',
    officialUrl: 'https://sajunaru.com',
    rating: null,
    reviewSummary: {
      aiSummary: '상담사의 직관력과 상황 파악 정확도에 대한 긍정 평가가 두드러집니다. 친근한 상담 분위기와 공감 능력을 장점으로 꼽는 후기가 많으며, 주요 상담 분야는 속마음·애정·재회 순입니다.',
      sentiment: 'positive',
      keywords: ['속마음', '애정', '재회', '금전/사업', '정확', '타로'],
      pros: ['\'어떻게 해도 괜찮은 안전한 이야기\'', '타로가 주는 진정한 위로는 공감이 아닌, 확신으로부터 오는 통찰력이라는 걸 명심하세요', '소름 돋는 적중률과 전문성에 감동'],
      cons: ['이 글을 보고 이거 광고후기 아니야', '라는 생각으로 후기를 찾아보고 있다면 후회하기 전에 마지막에 뭐라도 해보자 라는 생각을 하신다면 허니잼쌤이랑 상담 해보세요', '성격이 정말 정말 안 맞아서 연애 내내 싸웠다는 사람입니다'],
      sourceCount: 45,
      lastUpdated: '2026-03-02',
      sources: [
        { name: '블로그 후기 (티스토리)', url: 'https://ahddhuh.tistory.com/61', reviewCount: 2 },
        { name: '사주나루 이용자 후기', url: 'https://sajunaru.com/review.html#comment-7634438', reviewCount: 43 }
      ]
    },
    pricingDetail: {
      costPerUnit: '30초당 800~1,500원',
      avgCost15min: 33000,
      avgCost30min: 66000,
      costRange15min: [26400, 49500],
      vatIncluded: true,
      billingType: '분당과금',
      realCostExample: '30,000원 충전 시 인기 상담사(1,200원/30초)와 약 12분 30초 상담 가능'
    },
    consumerWarnings: [
      { type: 'caution', text: '무료 코인 10,000코인은 3일만 유효, 미사용 시 소멸' },
      { type: 'caution', text: '7일 초과 미사용 코인 환불 시 10% 수수료' },
      { type: 'caution', text: '채팅방 나가거나 앱 종료해도 구매 시간 계속 소진' },
      { type: 'tip', text: '신규 가입 시 10,000코인(3일 유효) 제공, 약 5분 상담 가능' }
    ],
    situationMatch: ['심야상담', '전문분석'],
  },
  {
    id: 'unse7',
    name: '운세7',
    type: '전화상담플랫폼',
    method: ['전화 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1~3만원',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: '다수',
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '신점·타로·사주 전문 상담사를 갖춘 분당 과금 방식 전화상담 플랫폼',
    officialUrl: 'https://www.unse7.com',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '충전 750원~/060 1,500원(30초)',
      avgCost15min: 33000,
      avgCost30min: 66000,
      costRange15min: [24750, 49500],
      vatIncluded: true,
      billingType: '분당과금',
      realCostExample: '충전상담 750원/30초 최저가, 15분=24,750원. 060 대비 최대 50% 할인'
    },
    consumerWarnings: [
      { type: 'positive', text: '충전상담 시 060 대비 최대 50% 할인' },
      { type: 'caution', text: '타임세일 카운트다운으로 충동결제 유도 가능성' },
      { type: 'tip', text: '리뷰 작성 시 적립금 1,000원 지급' }
    ],
    situationMatch: ['심야상담', '가성비최고'],
  },
  {
    id: 'unsedamda',
    name: '운세담다',
    type: '전화상담플랫폼',
    method: ['전화 상담', '채팅 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '타로', '신점'],
    priceRange: '1만원 이하',
    priceStructure: '분당과금',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: 0,
    operatingHours: null,
    summary: '저렴한 비용을 강조하는 전화·채팅 상담 플랫폼',
    officialUrl: 'https://www.unsedamda.com',
    rating: null,
    reviewSummary: {
      aiSummary: '균일가(1,000원/30초) 과금으로 가격 예측이 쉽고, 가입 시 적립금 10,000원을 제공하여 첫 상담 부담이 적습니다. 저렴한 비용을 강조하는 전화·채팅 상담 플랫폼입니다.',
      sentiment: 'positive',
      keywords: ['사주', '무료', '정확', '운세'],
      pros: ['정확한 상담을 위해서는', '무료 사주풀이는 사실', '무료로 사주풀이를 해주는 곳이'],
      cons: ['등 부담없이 이용이 가능합니다'],
      sourceCount: 2,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://koocker1.tistory.com/541', reviewCount: 2 }]
    },
    pricingDetail: {
      costPerUnit: '30초당 1,000원',
      avgCost15min: 33000,
      avgCost30min: 66000,
      costRange15min: [33000, 33000],
      vatIncluded: true,
      billingType: '분당과금',
      realCostExample: '코인 1,000원/30초 균일가, 15분=33,000원(VAT포함)'
    },
    consumerWarnings: [
      { type: 'tip', text: '가입 시 적립금 10,000원 제공' },
      { type: 'caution', text: '후기 작성은 5분 이상 상담 시에만 가능' }
    ],
    situationMatch: ['심야상담', '가성비최고'],
  },

  // ── 앱기반자동풀이 (11) ────────────────────────────────────────
  {
    id: 'jeomsin',
    name: '점신',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '건강', '진로/취업', '가족/관계'],
    counselingType: ['사주', '타로', '관상', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)', '웹'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: 996000,
    operatingHours: '24시간',
    summary: '누적 다운로드 1,700만, MAU 95만의 국내 1위 운세 앱. 관상·심리테스트 등 다양한 콘텐츠 제공',
    officialUrl: 'https://www.jeomsin.co.kr',
    rating: null,
    reviewSummary: {
      aiSummary: '국내 1위 운세 앱답게 다양한 콘텐츠(사주, 관상, 타로, 토정비결)와 무료 기능에 대한 만족도가 높습니다. 다만 광고 빈도와 유료 전환 유도에 대한 아쉬움도 일부 존재합니다. 배우 박성훈(전재준) 유퀴즈 출연 이후 인지도가 크게 상승했습니다.',
      sentiment: 'positive',
      keywords: ['타로', '사주', '앱', '운세', '무료', '정확'],
      pros: ['작년에는 운세의 정석이라는 어플을 이용하여 신년운세를 보았는데', '다른 어플을 이용하여 신년 운세와 토정비결을 보았다', '무료로 사주를 제공하는 이유가 있구나 싶다'],
      cons: ['단점은 광고가 조금 많이 뜬다는 점', '광고가 좀 뜨는데, 영상이라 길게 봐야 하는 광고는 아니고 잠깐 팝업으로 뜨는 광고라 오래 기다릴 필요는 없었다', '누르면 짧은 팝업 광고 하나 보고 전부 읽을 수 있다'],
      sourceCount: 25,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://xiaban.tistory.com/194', reviewCount: 25 }]
    },
    pricingDetail: {
      costPerUnit: '기본 무료, 행운패스/PRO 별도',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 55000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '기본 운세 무료. 전문가 전화상담 첫 3분 무료, 이후 분당과금. 점신PRO 55,000원'
    },
    consumerWarnings: [
      { type: 'caution', text: '일부 사용자가 광고 과다를 보고 (리뷰 95명 공감)' },
      { type: 'caution', text: '업데이트 후 무료 콘텐츠 범위가 축소된 사례 보고' },
      { type: 'tip', text: '광고 없이 이용하려면 행운패스 월정액 구독 필요' }
    ],
    situationMatch: ['가벼운재미', '전문분석', 'MZ감성'],
  },
  {
    id: 'postellar',
    name: '포스텔러',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '점성술', '별자리'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '누적 가입자 900만, 연 매출 100억 원 이상의 MZ세대 대표 운세 앱. 사주·타로·점성술 통합',
    officialUrl: 'https://postellar.com',
    rating: null,
    reviewSummary: {
      aiSummary: '사주·타로·점성술을 통합한 MZ세대 대표 운세 앱으로, 직관적인 UI와 만세력 정확도에 대한 호평이 많습니다. 누적 가입자 900만, 연 매출 100억 원 이상의 검증된 플랫폼입니다.',
      sentiment: 'positive',
      keywords: ['타로', '사주', '운세', '정확', '무료', '앱'],
      pros: ['누군가 당신을 칭찬했을 때 보다 듣기 좋은 말은', '- 대단하다와 재미있다 둘다 굉장히 좋은 말이지만, 저는 유머있다는 말을 더 좋아하기 때문에 재미있다를 선택하였습니다', '근데 이건 좀 애매하긴 한게 사람의 마음을 제가 정확히 다 눈치 챘다고 하는것도 좀 건방진것 같기도 하고, 솔직히 정확히는 모르는 것이죠'],
      cons: ['개인별로 숨겨진 심리와 도화살을 분석하여 매력을 발견할 수 있도록 고안한 테스트', '저는 성격이 정말 급한편이라서 연락이 오면 바로바로 받고, 제가 남에게 연락을 할때도 그 사람이 빨리 받지 않으면 조금 짜증이 나는 편입니다', '재미로 하는거라서 크게 신경은 안쓰지만, 결과가 조금 실망스럽습니다'],
      sourceCount: 6,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://hodorijjang.tistory.com/480', reviewCount: 6 }]
    },
    pricingDetail: {
      costPerUnit: '기본 무료, 프리미엄 콘텐츠 유료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 20000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '기본 운세 무료. 심층 콘텐츠 건당 3,000~20,000원'
    },
    consumerWarnings: [
      { type: 'tip', text: '무료 기본 운세 콘텐츠는 광고 없이 이용 가능' },
      { type: 'caution', text: '심층 콘텐츠는 개별 유료 구매 방식 (건당 3,000~20,000원)' },
      { type: 'caution', text: '결제 후 앱 오류 시 고객센터 응답 지연 가능성' }
    ],
    situationMatch: ['가벼운재미', 'MZ감성', '전문분석'],
  },
  {
    id: 'unsebigul',
    name: '운세비결',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운'],
    counselingType: ['토정비결', '사주', '오늘의 운세'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '토정비결·신년운세 중심의 운세 앱, 사용 편리성 호평',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '운세비결 기본 운세 무료, 일부 심층 콘텐츠 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['전문분석'],
  },
  {
    id: 'ujucat-bora',
    name: '우주고양이 보라',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: 'iOS 운세 앱 평점 1위(4.8점), KAIST 연구진과 유명 사주가 4인이 협업한 MZ 연애운 특화 앱',
    officialUrl: null,
    rating: 4.8,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '우주고양이 보라 기본 운세 무료, 연애 심층 리딩 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['MZ감성', '연애특화', '가벼운재미'],
  },
  {
    id: 'ozstarot',
    name: '오즈의타로',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '투시타로로 인기를 얻은 타로 전문 앱, 인터페이스와 배경음악 호평',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '오즈의타로 기본 타로 무료, 프리미엄 리딩 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['위로공감', '연애특화'],
  },
  {
    id: 'jeongtong-saju',
    name: '정통사주',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업', '건강', '진로/취업'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '건당정액',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '50가지 이상 정통 사주 콘텐츠를 제공하는 명리학 기반 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '건당정액',
      realCostExample: '정통사주 기본 기능 무료, 상세 해석은 건당 결제(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['전문분석', '논리분석형'],
  },
  {
    id: 'inyeon',
    name: '인연궁합',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합'],
    counselingType: ['사주'],
    priceRange: '1~3만원',
    priceStructure: '건당정액',
    extraCharges: false,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '궁합 전문 앱, 한 번 결제(22,000원~)로 여러 생년월일 비교 가능',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '건당정액',
      realCostExample: '인연궁합 기본 정보 무료, 궁합 리포트 건당 결제(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['연애특화'],
  },
  {
    id: 'hwangje-unse',
    name: '황제운세',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '토정비결', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '무료 운세·사주·궁합·토정비결·꿈해몽을 제공하는 종합 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '황제운세 기본 운세 무료, 일부 프리미엄 콘텐츠 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['가벼운재미', '가성비최고'],
  },
  {
    id: 'mytarot',
    name: '마이타로',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이', 'AI 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['타로', '사주', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '정통 명리학 사주풀이와 AI 기반 타로 리딩을 결합한 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '마이타로 기본 운세 무료, AI 심층 상담 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['MZ감성', '연애특화'],
  },
  {
    id: 'unsudowon',
    name: '운수도원 투데이',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '오늘의 운세'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '궁합·연애스타일 분석에 호평을 받는 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '운수도원 투데이 기본 운세 무료, 일부 확장 리딩 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['가벼운재미', '가성비최고'],
  },
  {
    id: 'unsebichaek',
    name: '운세비책',
    type: '앱기반자동풀이',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '신년운세·사주·궁합 풀이를 제공하는 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '운세비책 기본 운세 무료, 일부 심화 풀이 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['가벼운재미'],
  },

  // ── AI운세 (6) ─────────────────────────────────────────────────
  {
    id: 'hellobot',
    name: '헬로우봇',
    type: 'AI운세',
    method: ['앱 자동 풀이', 'AI 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '누적 다운로드 100만+, AI 챗봇 기반 타로·사주·별자리·손금 통합 상담 앱',
    officialUrl: 'https://hellobot.co',
    rating: null,
    reviewSummary: {
      aiSummary: 'AI 챗봇 기반으로 타로·사주·별자리·손금 등 200가지 이상의 무료 콘텐츠를 제공합니다. 대화형 인터페이스가 MZ세대에 호평받고 있으며, 보석(인앱 화폐) 소모 속도에 대한 의견이 엇갈립니다.',
      sentiment: 'positive',
      keywords: ['타로', '사주', '운세', 'AI', '정확'],
      pros: ['그냥 잘 맞는데 한 군데가 최고', '좀 신기한게 일주만 해도 숫자가 어마어마한디,,', '\" 싶을 정도의 정확한 분석'],
      cons: ['내가 장담하건대, 헬로우봇 보고 후회할 일은 없을거애오', '여행지에서는 안맞는다고 하는 거', '후회를 하고 있을까 자괴감이 옴총 들었슴^,^'],
      sourceCount: 10,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://1spoon-creator.tistory.com/24', reviewCount: 10 }]
    },
    pricingDetail: {
      costPerUnit: '무료+보석(인앱화폐)',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 26000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '200가지+ 무료. 유료 콘텐츠 약 5,000원~. 라마마VIP 월 26,000원'
    },
    consumerWarnings: [
      { type: 'caution', text: '결제 후 콘텐츠 접근 불가 문제 일부 보고' },
      { type: 'caution', text: '보석(인앱 화폐) 소모가 빠르다는 의견 있음' },
      { type: 'tip', text: '결제 전 반드시 로그인 상태를 확인하세요 (비로그인 결제 시 콘텐츠 소멸 위험)' }
    ],
    situationMatch: ['위로공감', 'MZ감성', 'AI즉시결과'],
  },
  {
    id: 'hori-ai',
    name: '호리AI',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업'],
    counselingType: ['사주', '타로', '점성술'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '사주·타로·점성술·자미두수 등을 AI가 직접 계산·해석하는 무료 베타 서비스',
    officialUrl: 'https://hori.chat',
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '무료(베타)',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '현재 전체 무료 베타 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['AI즉시결과', '가성비최고', '논리분석형'],
  },
  {
    id: 'dosa-ai',
    name: '도사',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['종합운', '연애/궁합', '재물/사업', '진로/취업'],
    counselingType: ['사주', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: '천문 데이터 기반 정밀 사주 계산과 24시간 AI 상담을 제공하는 AI 사주 플랫폼',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료, 프리미엄 리딩 유료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '도사 AI 기본 상담 무료, 확장 해석 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['AI즉시결과', 'MZ감성'],
  },
  {
    id: 'annyeong-tarot',
    name: '안녕타로',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['타로'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: 'AI 타로 마스터와 대화하며 고민을 해결하는 AI 타로 운세 앱',
    officialUrl: null,
    rating: null,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료, 프리미엄 타로 리딩 유료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '안녕타로 기본 상담 무료, 심층 카드 해석 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['AI즉시결과', '위로공감', '연애특화'],
  },
  {
    id: 'unsewiki',
    name: '운세위키',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운', '재물/사업', '진로/취업'],
    counselingType: ['사주'],
    priceRange: '1만원 이하',
    priceStructure: '건당정액',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 27227,
    operatingHours: '24시간',
    summary: '1982년 정통 사주명리 기반 AI 분석, 누적 20만+ 이용자. 토스 파트너사, 동아일보 브랜드 대상 수상',
    officialUrl: 'https://luckyloveme.com',
    rating: 4.8,
    reviewSummary: {
      aiSummary: '정통 사주명리 기반 AI 분석으로 빠른 결과 확인이 가능하며, 토스 파트너사로서의 신뢰도를 바탕으로 누적 20만+ 이용자를 보유하고 있습니다. 후기 데이터 추가 수집이 진행 중입니다.',
      sentiment: 'neutral',
      keywords: ['사주'],
      pros: [],
      cons: [],
      sourceCount: 1,
      lastUpdated: '2026-03-02',
      sources: [{ name: '운세위키 이용자 후기', url: 'https://luckyloveme.com/reviews', reviewCount: 1 }]
    },
    pricingDetail: {
      costPerUnit: '기본 무료, 심층 리포트 유료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '운세위키 기본 결과 무료, 전문 리포트 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['AI즉시결과', '논리분석형', '전문분석'],
  },
  {
    id: 'zendi',
    name: '젠디',
    type: 'AI운세',
    method: ['AI 상담'],
    specialty: ['연애/궁합', '종합운'],
    counselingType: ['사주', '타로'],
    priceRange: '1만원 이하',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: true,
    reviewCount: null,
    operatingHours: '24시간',
    summary: 'App Store 평점 4.9, 현대적 감각으로 사주를 재해석하는 AI 채팅 운세 앱',
    officialUrl: null,
    rating: 4.9,
    reviewSummary: { aiSummary: null, sentiment: null, keywords: [], pros: [], cons: [], sourceCount: 0, lastUpdated: null, sources: [] },
    pricingDetail: {
      costPerUnit: '기본 무료, 프리미엄 채팅 유료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 10000],
      vatIncluded: true,
      billingType: '무료+부분유료',
      realCostExample: '젠디 기본 운세 무료, 고급 상담 모드 유료(최대 10,000원)'
    },
    consumerWarnings: [],
    situationMatch: ['AI즉시결과', 'MZ감성', '연애특화'],
  },

  // ── 포털무료운세 (3) ───────────────────────────────────────────
  {
    id: 'naver-unse',
    name: '네이버 운세',
    type: '포털무료운세',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '오늘의 운세', '토정비결', '별자리'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹', '앱(iOS)', '앱(Android)'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '접근성 최고의 포털 무료 운세, 간결한 해석 제공',
    officialUrl: 'https://search.naver.com/search.naver?query=운세',
    rating: null,
    reviewSummary: {
      aiSummary: '공개 커뮤니티에서 수집한 4건의 후기를 분석한 결과, 전반적으로 긍정적 평가입니다. 주요 상담 분야는 타로입니다.',
      sentiment: 'positive',
      keywords: ['타로', '무료', '정확', 'AI'],
      pros: ['무료사주 사이트 추천 TOP 5 | 2026년 신년운세·토정비결', '무료사주 사이트 추천 BEST 5', '무료로 신년 사주와 토정비결을 확인할 수 있는 사이트를 찾는 분들이 많습니다'],
      cons: ['별도의 회원가입이 필요 없어 부담 없이 이용할 수 있습니다', '• 부담 없이 시작', '결과가 좋게 나오면 기분 좋게 받아들이고, 저처럼 조금 아쉬운 결과가 나오더라도 AI의 조언을 삼아 더 나은 방향을 찾으시면 됩니다'],
      sourceCount: 4,
      lastUpdated: '2026-03-02',
      sources: [{ name: '블로그 후기 (티스토리)', url: 'https://unitypath.tistory.com/47', reviewCount: 4 }]
    },
    pricingDetail: {
      costPerUnit: '무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '완전 무료 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['가벼운재미', '가성비최고'],
  },
  {
    id: 'nate-unse',
    name: '네이트 운세',
    type: '포털무료운세',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '무료 기본 운세와 다양한 유료 프리미엄 콘텐츠를 제공하는 포털 운세',
    officialUrl: 'https://m.fortune.nate.com',
    rating: null,
    reviewSummary: {
      aiSummary: '포털 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '포털'],
      pros: ['기본 운세 무료 제공'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
    pricingDetail: {
      costPerUnit: '무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '완전 무료 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['가벼운재미', '가성비최고'],
  },
  {
    id: 'fortuneaid',
    name: '포춘에이드',
    type: '포털무료운세',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '타로', '점성술', '별자리', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료+부분유료',
    extraCharges: true,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '동서양 운세를 폭넓게 다루는 무료 운세 포털',
    officialUrl: 'https://www.fortunade.com',
    rating: null,
    reviewSummary: {
      aiSummary: '포털 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '포털'],
      pros: ['콘텐츠 폭이 넓음'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
    pricingDetail: {
      costPerUnit: '무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '완전 무료 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['가벼운재미', '가성비최고'],
  },

  // ── 기업제공무료 (3) ───────────────────────────────────────────
  {
    id: 'shinhan-unse',
    name: '신한라이프 운세',
    type: '기업제공무료',
    method: ['앱 자동 풀이'],
    specialty: ['종합운'],
    counselingType: ['사주', '오늘의 운세'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '평생운세 풀이에 호평을 받는 신한라이프 무료 운세 서비스',
    officialUrl: 'https://www.shinhanlife.co.kr',
    rating: null,
    reviewSummary: {
      aiSummary: '기업 제공 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '기업제공'],
      pros: ['무료 제공'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
    pricingDetail: {
      costPerUnit: '무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '완전 무료 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['가성비최고'],
  },
  {
    id: 'nonghyup-unse',
    name: '농협 운세',
    type: '기업제공무료',
    method: ['앱 자동 풀이'],
    specialty: ['종합운'],
    counselingType: ['사주', '오늘의 운세', '토정비결'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '100% 무료, 이용자 호평이 많은 농협 제공 운세 서비스 (PC 전용)',
    officialUrl: 'https://www.nonghyup.com',
    rating: null,
    reviewSummary: {
      aiSummary: '기업 제공 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '기업제공'],
      pros: ['완전 무료'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
    pricingDetail: {
      costPerUnit: '무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '완전 무료 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['가성비최고'],
  },
  {
    id: 'asiae-unse',
    name: '아시아경제 운세',
    type: '기업제공무료',
    method: ['앱 자동 풀이'],
    specialty: ['종합운', '연애/궁합', '재물/사업'],
    counselingType: ['사주', '오늘의 운세', '토정비결', '궁합'],
    priceRange: '무료',
    priceStructure: '무료',
    extraCharges: false,
    freeTrial: null,
    platform: ['웹'],
    counselorCount: null,
    signupRequired: false,
    reviewCount: 0,
    operatingHours: '24시간',
    summary: '아시아경제 천기누설 브랜드, 정통사주·궁합·토정비결·이름풀이를 제공하는 언론사 무료 운세',
    officialUrl: 'https://www.asiae.co.kr/fortune/index.htm',
    rating: null,
    reviewSummary: {
      aiSummary: '언론사 제공 무료 운세 서비스 특성상 공개 후기 집계 체계가 제한적이며 별도 후기 데이터가 제공되지 않습니다.',
      sentiment: 'neutral',
      keywords: ['무료', '언론사'],
      pros: ['전통 사주·궁합 콘텐츠 풍부'],
      cons: ['후기 데이터 부족'],
      sourceCount: 0,
      lastUpdated: '2026-03-02',
      sources: []
    },
    pricingDetail: {
      costPerUnit: '무료',
      avgCost15min: 0,
      avgCost30min: 0,
      costRange15min: [0, 0],
      vatIncluded: true,
      billingType: '무료',
      realCostExample: '완전 무료 서비스'
    },
    consumerWarnings: [],
    situationMatch: ['가성비최고', '전문분석'],
  },
];

/** @type {ConsultationType[]} */
const CONSULTATION_TYPES = [
  { id: 'love', name: '연애/궁합', keywords: ['연애운', '궁합', '속마음', '재회', '결혼', '썸'] },
  { id: 'career', name: '진로/취업', keywords: ['이직', '취업', '적성', '직업운'] },
  { id: 'wealth', name: '재물/사업', keywords: ['재물운', '사업운', '투자', '금전'] },
  { id: 'health', name: '건강', keywords: ['건강운', '질병'] },
  { id: 'general', name: '종합운', keywords: ['신년운세', '토정비결', '평생운', '인생총운'] },
  { id: 'family', name: '가족/관계', keywords: ['부모', '자녀', '직장 인간관계'] },
];

/** @type {ServiceType[]} */
const SERVICE_TYPES = [
  { id: 'phone', name: '전화상담플랫폼', icon: '📞' },
  { id: 'app', name: '앱기반자동풀이', icon: '📱' },
  { id: 'ai', name: 'AI운세', icon: '🤖' },
  { id: 'portal', name: '포털무료운세', icon: '🌐' },
  { id: 'corporate', name: '기업제공무료', icon: '🏢' },
  { id: 'offline', name: '오프라인점집', icon: '🏠' },
  { id: 'tarotcafe', name: '타로카페', icon: '☕' },
];

/** @type {Method[]} */
const METHODS = [
  { id: 'phone', name: '전화 상담', desc: '실시간 음성, 즉각 피드백' },
  { id: 'chat', name: '채팅 상담', desc: '텍스트 기반, 기록 남음' },
  { id: 'visit', name: '대면 상담', desc: '직접 방문, 현장감' },
  { id: 'auto', name: '앱 자동 풀이', desc: '즉시 결과, 저렴/무료' },
  { id: 'ai', name: 'AI 상담', desc: '24시간, 무료~저가' },
];

/** @type {PriceRange[]} */
const PRICE_RANGES = [
  { id: 'free', name: '무료', max: 0 },
  { id: 'under10k', name: '1만원 이하', max: 10000 },
  { id: '10k-30k', name: '1~3만원', min: 10000, max: 30000 },
  { id: '30k-50k', name: '3~5만원', min: 30000, max: 50000 },
  { id: 'over50k', name: '5만원 이상', min: 50000 },
];

/** @type {ReviewDigest[]} */
const REVIEWS = [
  {
    id: 'chunmyung-2026q1',
    serviceId: 'chunmyung',
    period: '2026-Q1',
    aiSummary: '건당 고정가(3.5~5만원) 방식으로 시간 걱정 없이 상담받을 수 있다는 점이 큰 장점입니다. 엄격한 상담사 입점 심사로 신뢰성을 강조하며, 후기 40만 건 이상을 보유한 대표 전화상담 플랫폼입니다.',
    sentiment: 'positive',
    keywords: ['타로', '사주', '정확', 'AI', '궁합'],
    pros: ['이번에 후기를 남길 잠실 주리 선생님 사주 상담은 천명이라는 서비스를 이용하였습니다', '이번에 처음 써봤는데 생각보다 괜찮았습니다', '자세한 후기를 남기기 전에 결론부터 말씀드리자면 꽤나 만족스러운 사주 상담이었습니다'],
    cons: ['가격이 꽤나 부담되죠', '리뷰 원탑이니 가격이 부담되어도 믿고 가는 것으로 결정', '꽤나 부담되는 가격, 30분에 55,000원이니까요'],
    sourceCount: 8,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://trueteller.tistory.com/3', reviewCount: 8 }
    ]
  },
  {
    id: 'hellobot-2026q1',
    serviceId: 'hellobot',
    period: '2026-Q1',
    aiSummary: 'AI 챗봇 기반으로 타로·사주·별자리·손금 등 200가지 이상의 무료 콘텐츠를 제공합니다. 대화형 인터페이스가 MZ세대에 호평받고 있으며, 보석(인앱 화폐) 소모 속도에 대한 의견이 엇갈립니다.',
    sentiment: 'positive',
    keywords: ['타로', '사주', '운세', 'AI', '정확'],
    pros: ['그냥 잘 맞는데 한 군데가 최고', '좀 신기한게 일주만 해도 숫자가 어마어마한디,,', '\" 싶을 정도의 정확한 분석'],
    cons: ['내가 장담하건대, 헬로우봇 보고 후회할 일은 없을거애오', '여행지에서는 안맞는다고 하는 거', '후회를 하고 있을까 자괴감이 옴총 들었슴^,^'],
    sourceCount: 10,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://1spoon-creator.tistory.com/24', reviewCount: 10 }
    ]
  },
  {
    id: 'jeomsin-2026q1',
    serviceId: 'jeomsin',
    period: '2026-Q1',
    aiSummary: '국내 1위 운세 앱답게 다양한 콘텐츠(사주, 관상, 타로, 토정비결)와 무료 기능에 대한 만족도가 높습니다. 다만 광고 빈도와 유료 전환 유도에 대한 아쉬움도 일부 존재합니다. 배우 박성훈(전재준) 유퀴즈 출연 이후 인지도가 크게 상승했습니다.',
    sentiment: 'positive',
    keywords: ['타로', '사주', '앱', '운세', '무료', '정확'],
    pros: ['작년에는 운세의 정석이라는 어플을 이용하여 신년운세를 보았는데', '다른 어플을 이용하여 신년 운세와 토정비결을 보았다', '무료로 사주를 제공하는 이유가 있구나 싶다'],
    cons: ['단점은 광고가 조금 많이 뜬다는 점', '광고가 좀 뜨는데, 영상이라 길게 봐야 하는 광고는 아니고 잠깐 팝업으로 뜨는 광고라 오래 기다릴 필요는 없었다', '누르면 짧은 팝업 광고 하나 보고 전부 읽을 수 있다'],
    sourceCount: 25,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://xiaban.tistory.com/194', reviewCount: 25 }
    ]
  },
  {
    id: 'naver-unse-2026q1',
    serviceId: 'naver-unse',
    period: '2026-Q1',
    aiSummary: '공개 커뮤니티에서 수집한 4건의 후기를 분석한 결과, 전반적으로 긍정적 평가입니다. 주요 상담 분야는 타로입니다.',
    sentiment: 'positive',
    keywords: ['타로', '무료', '정확', 'AI'],
    pros: ['무료사주 사이트 추천 TOP 5 | 2026년 신년운세·토정비결', '무료사주 사이트 추천 BEST 5', '무료로 신년 사주와 토정비결을 확인할 수 있는 사이트를 찾는 분들이 많습니다'],
    cons: ['별도의 회원가입이 필요 없어 부담 없이 이용할 수 있습니다', '• 부담 없이 시작', '결과가 좋게 나오면 기분 좋게 받아들이고, 저처럼 조금 아쉬운 결과가 나오더라도 AI의 조언을 삼아 더 나은 방향을 찾으시면 됩니다'],
    sourceCount: 4,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://unitypath.tistory.com/47', reviewCount: 4 }
    ]
  },
  {
    id: 'postellar-2026q1',
    serviceId: 'postellar',
    period: '2026-Q1',
    aiSummary: '사주·타로·점성술을 통합한 MZ세대 대표 운세 앱으로, 직관적인 UI와 만세력 정확도에 대한 호평이 많습니다. 누적 가입자 900만, 연 매출 100억 원 이상의 검증된 플랫폼입니다.',
    sentiment: 'positive',
    keywords: ['타로', '사주', '운세', '정확', '무료', '앱'],
    pros: ['누군가 당신을 칭찬했을 때 보다 듣기 좋은 말은', '- 대단하다와 재미있다 둘다 굉장히 좋은 말이지만, 저는 유머있다는 말을 더 좋아하기 때문에 재미있다를 선택하였습니다', '근데 이건 좀 애매하긴 한게 사람의 마음을 제가 정확히 다 눈치 챘다고 하는것도 좀 건방진것 같기도 하고, 솔직히 정확히는 모르는 것이죠'],
    cons: ['개인별로 숨겨진 심리와 도화살을 분석하여 매력을 발견할 수 있도록 고안한 테스트', '저는 성격이 정말 급한편이라서 연락이 오면 바로바로 받고, 제가 남에게 연락을 할때도 그 사람이 빨리 받지 않으면 조금 짜증이 나는 편입니다', '재미로 하는거라서 크게 신경은 안쓰지만, 결과가 조금 실망스럽습니다'],
    sourceCount: 6,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://hodorijjang.tistory.com/480', reviewCount: 6 }
    ]
  },
  {
    id: 'sajochungung-2026q1',
    serviceId: 'sajochungung',
    period: '2026-Q1',
    aiSummary: '리얼후기 131만 건, 상담사 500여 명 규모의 국내 최대 전화상담 플랫폼입니다. 상담사 선택 폭이 넓고 24시간 연결 가능하다는 장점이 있으나, 분당 과금 방식으로 장시간 상담 시 비용 부담이 있을 수 있습니다.',
    sentiment: 'positive',
    keywords: ['타로', '무료', '정확', '운세'],
    pros: ['무료 재회 신점 완벽 가이드', '이별 후 1년간 각종 무료/유료 신점을 경험하고, 현재는 명리학을 공부하고 있는 30대 직장인입니다', '오늘은 제가 실제로 경험한 무료 재회 신점의 모든 것을 진솔하게 나누고자 합니다'],
    cons: ['- 장점: 부담 없는 접근성', '- 단점: 비용 부담', '2) 사기 사이트 구별법'],
    sourceCount: 2,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://caomeiyun3.tistory.com/197', reviewCount: 2 }
    ]
  },
  {
    id: 'sajoonaru-2026q1',
    serviceId: 'sajoonaru',
    period: '2026-Q1',
    aiSummary: '상담사의 직관력과 상황 파악 정확도에 대한 긍정 평가가 두드러집니다. 친근한 상담 분위기와 공감 능력을 장점으로 꼽는 후기가 많으며, 주요 상담 분야는 속마음·애정·재회 순입니다.',
    sentiment: 'positive',
    keywords: ['속마음', '애정', '재회', '금전/사업', '정확', '타로'],
    pros: ['\'어떻게 해도 괜찮은 안전한 이야기\'', '타로가 주는 진정한 위로는 공감이 아닌, 확신으로부터 오는 통찰력이라는 걸 명심하세요', '소름 돋는 적중률과 전문성에 감동'],
    cons: ['이 글을 보고 이거 광고후기 아니야', '라는 생각으로 후기를 찾아보고 있다면 후회하기 전에 마지막에 뭐라도 해보자 라는 생각을 하신다면 허니잼쌤이랑 상담 해보세요', '성격이 정말 정말 안 맞아서 연애 내내 싸웠다는 사람입니다'],
    sourceCount: 45,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://ahddhuh.tistory.com/61', reviewCount: 2 },
      { name: '사주나루 이용자 후기', url: 'https://sajunaru.com/review.html#comment-7634438', reviewCount: 43 }
    ]
  },
  {
    id: 'ssintong-2026q1',
    serviceId: 'ssintong',
    period: '2026-Q1',
    aiSummary: 'MZ세대를 타깃으로 고화질 영상 상담을 도입한 신흥 전화상담 플랫폼입니다. 2025년 출시 이후 빠르게 성장하고 있으며, 사주·타로·신점 전문 상담사를 갖추고 있습니다.',
    sentiment: 'positive',
    keywords: ['사주', '정확', '무료'],
    pros: ['그렇게 유니아 수녀는 과거 자신의 동료 수녀였으나 현재 무당인 \'효원\'(김국희 배우)에게 도움을 청해 희준을 구하기 위한 의식들을 시도해 보지만 이 방법 역시 신', '그러나 배우들의 연기가 전반적으로 좋았고 시각적 연출에 심혈을 기울인 듯하여 볼거리가 나름 많았던 부분은 긍정적으로 보였던 것 같아요', '함께 보면 좋은 글'],
    cons: ['그 부분이 조금 아쉬웠어요', '한국의 역사기록은 앞서도 언급하였듯이 약소국의', '사기」와「삼국유사」뿐이다'],
    sourceCount: 4,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://lucky-hee.tistory.com/251', reviewCount: 4 }
    ]
  },
  {
    id: 'unsedamda-2026q1',
    serviceId: 'unsedamda',
    period: '2026-Q1',
    aiSummary: '균일가(1,000원/30초) 과금으로 가격 예측이 쉽고, 가입 시 적립금 10,000원을 제공하여 첫 상담 부담이 적습니다. 저렴한 비용을 강조하는 전화·채팅 상담 플랫폼입니다.',
    sentiment: 'positive',
    keywords: ['사주', '무료', '정확', '운세'],
    pros: ['정확한 상담을 위해서는', '무료 사주풀이는 사실', '무료로 사주풀이를 해주는 곳이'],
    cons: ['등 부담없이 이용이 가능합니다'],
    sourceCount: 2,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '블로그 후기 (티스토리)', url: 'https://koocker1.tistory.com/541', reviewCount: 2 }
    ]
  },
  {
    id: 'unsewiki-2026q1',
    serviceId: 'unsewiki',
    period: '2026-Q1',
    aiSummary: '정통 사주명리 기반 AI 분석으로 빠른 결과 확인이 가능하며, 토스 파트너사로서의 신뢰도를 바탕으로 누적 20만+ 이용자를 보유하고 있습니다. 후기 데이터 추가 수집이 진행 중입니다.',
    sentiment: 'neutral',
    keywords: ['사주'],
    pros: [],
    cons: [],
    sourceCount: 1,
    lastUpdated: '2026-03-02',
    sources: [
      { name: '운세위키 이용자 후기', url: 'https://luckyloveme.com/reviews', reviewCount: 1 }
    ]
  }
];

/** @type {Article[]} */
const ARTICLES = [
  {
    id: 'phone-taro-top5',
    title: '전화 타로 플랫폼 5곳 비교 - 가격·후기·특징 정리',
    category: '비교분석',
    slug: 'phone-taro-top5',
    publishedAt: '2026-03-02',
    summary: '대표 전화 타로 플랫폼 5곳의 가격 구조와 후기 경향을 한 페이지에서 비교합니다.',
    tags: ['전화타로', '가격비교', '후기요약'],
  },
  {
    id: 'saju-vs-taro-vs-sinjeom',
    title: '사주 vs 타로 vs 신점, 나에게 맞는 운세는?',
    category: '초보자가이드',
    slug: 'saju-vs-taro-vs-sinjeom',
    publishedAt: '2026-03-02',
    summary: '처음 운세를 보는 사람을 위해 상담 종류별 특징과 선택 기준을 정리했습니다.',
    tags: ['사주', '타로', '신점'],
  },
  {
    id: 'fortune-price-guide',
    title: '운세 상담, 얼마를 써야 적당할까? 가격 총정리',
    category: '가격가이드',
    slug: 'fortune-price-guide',
    publishedAt: '2026-03-02',
    summary: '무료부터 분당 과금까지, 운세 서비스 가격을 예산 구간별로 정리합니다.',
    tags: ['운세가격', '예산', '분당과금'],
  },
  {
    id: 'ai-fortune-review',
    title: 'AI 운세 서비스, 실제로 써보니 - 호리AI·아리사주 비교',
    category: '트렌드',
    slug: 'ai-fortune-review',
    publishedAt: '2026-03-02',
    summary: 'AI 운세 서비스의 장점과 한계를 사용 흐름 기준으로 비교 분석합니다.',
    tags: ['AI운세', '호리AI', '아리사주'],
  },
  {
    id: 'app-fortune-comparison',
    title: '점신 vs 포스텔러 vs 헬로우봇 - 운세 앱 3대장 비교',
    category: '비교분석',
    slug: 'app-fortune-comparison',
    publishedAt: '2026-03-02',
    summary: '국내 대표 운세 앱 3종의 콘텐츠 구성과 과금 구조를 비교합니다.',
    tags: ['점신', '포스텔러', '헬로우봇'],
  },
];

/** @type {Brand} */
const BRAND = {
  name: '보다',
  nameEn: 'BODA',
  tagline: '운세를 보다, 더 보다 나은 선택',
  email: 'hello@unsetok.com',
  domain: 'unsetok.com',
  url: 'https://unsetok.com',
  disclaimer:
    'BODA는 운세 서비스의 정보를 비교·제공하는 플랫폼이며, 특정 서비스의 효과나 정확성을 보증하지 않습니다. 서비스 이용에 따른 결과는 이용자 본인의 판단과 책임 하에 이루어집니다. 운세 상담은 참고용이며, 중요한 의사결정은 전문가(의료/법률/재무 등)와 상의하시기 바랍니다.',
};

// Browser + Node.js compatibility.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SERVICES, CONSULTATION_TYPES, SERVICE_TYPES, METHODS, PRICE_RANGES, REVIEWS, ARTICLES, BRAND };
} else {
  window.BODA_DATA = { SERVICES, CONSULTATION_TYPES, SERVICE_TYPES, METHODS, PRICE_RANGES, REVIEWS, ARTICLES, BRAND };
}
