const fs = require('fs');
fs.appendFileSync('index.html', Buffer.from('PGhlYWRlciBjbGFzcz0naGVhZGVyJz4=', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICA8ZGl2IGNsYXNzPSdoZWFkZXItaW5uZXInPg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgIDxkaXYgY2xhc3M9J2xvZ28nPg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGRpdiBjbGFzcz0nbG9nby1tYXJrJz4mIzEyODE0Mjs8L2Rpdj4=', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGRpdiBjbGFzcz0nbG9nby10ZXh0Jz4mIzQ0NTQ0OyYjNDcwMTY7PHNwYW4+JiM1MzY4NTs8L3NwYW4+PC9kaXY+', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgIDwvZGl2Pg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgIDxkaXYgY2xhc3M9J2hlYWRlci1zZWFyY2gnPg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGlucHV0IHR5cGU9J3RleHQnIHBsYWNlaG9sZGVyPSfsi5zsiKDrqoUsIOuzkeybkCwg6rOg66+87J2EIOqygOyDie2VtOuztOyEuOyalCcgdmFsdWU9Jyc+', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPHNwYW4gY2xhc3M9J3NlYXJjaC1pY29uJz4mIzEyODI2OTs8L3NwYW4+', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgIDwvZGl2Pg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgIDxkaXYgY2xhc3M9J2hlYWRlci1hY3Rpb25zJz4=', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGJ1dHRvbiBjbGFzcz0nYnRuLWljb24nIG9uY2xpY2s9J3Nob3dUb2FzdChjaHIzOeyVjOumvGNocjM5KScgdGl0bGU9J+yVjOumvCc+JiMxMjgyNzY7PHNwYW4gY2xhc3M9J2JhZGdlJz4zPC9zcGFuPjwvYnV0dG9uPg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGJ1dHRvbiBjbGFzcz0nYnRuLWljb24nIHRpdGxlPSfsoIDsnqXtlagnPiYjMTI4Mjc4OzwvYnV0dG9uPg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGJ1dHRvbiBjbGFzcz0nYnRuLXdyaXRlJyBvbmNsaWNrPSdzaG93VG9hc3QoY2hyMznquIDsk7DquLBjaHIzOSknPiYjOTk5OTsmIzY1MDM5OyDquIDsk7DquLA8L2J1dHRvbj4=', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgICAgPGRpdiBjbGFzcz0nYXZhdGFyLXNtJz4mIzEyNzgwMDs8L2Rpdj4=', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICAgIDwvZGl2Pg==', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('ICA8L2Rpdj4=', 'base64').toString('utf8') + '\n', 'utf8');
fs.appendFileSync('index.html', Buffer.from('PC9oZWFkZXI+', 'base64').toString('utf8') + '\n', 'utf8');
console.log('header done', fs.statSync('index.html').size);