const fs = require('fs');
const ap = s => fs.appendFileSync('index.html', s + '\n', 'utf8');
ap('.modal-overlay{position:fixed;inset:0;background:rgba(42,35,32,.6);backdrop-filter:blur(4px);z-index:200;display:flex;align-items:center;justify-content:center;padding:20px;opacity:0;pointer-events:none;transition:opacity .25s ease}');
ap('.modal-overlay.open{opacity:1;pointer-events:all}');
ap('.modal-box{background:var(--white);border-radius:var(--radius-xl);width:100%;max-width:780px;max-height:90vh;overflow-y:auto;box-shadow:var(--shadow-lg);transform:translateY(20px);transition:transform .25s ease;position:relative}');
ap('.modal-overlay.open .modal-box{transform:translateY(0)}');
ap('.modal-close{position:absolute;top:16px;right:16px;width:36px;height:36px;border-radius:50%;background:rgba(42,35,32,.08);display:flex;align-items:center;justify-content:center;font-size:18px;color:var(--ink);transition:var(--transition);z-index:10}');
ap('.modal-close:hover{background:rgba(42,35,32,.15)}');
ap('.modal-gallery{position:relative;background:var(--charcoal);border-radius:var(--radius-xl) var(--radius-xl) 0 0;overflow:hidden}');
ap('.gallery-main{aspect-ratio:16/9;position:relative;overflow:hidden;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,#3A1A28,#5A2A40)}');
ap('.gallery-nav{position:absolute;top:50%;transform:translateY(-50%);width:36px;height:36px;background:rgba(255,255,255,.2);backdrop-filter:blur(4px);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:16px;color:white;transition:var(--transition);z-index:5}');
ap('.gallery-nav:hover{background:rgba(255,255,255,.35)}');
ap('.gallery-nav.prev{left:12px}');
ap('.gallery-nav.next{right:12px}');
ap('.gallery-dots{position:absolute;bottom:12px;left:50%;transform:translateX(-50%);display:flex;gap:6px}');
ap('.gallery-dot{width:6px;height:6px;border-radius:50%;background:rgba(255,255,255,.4);transition:var(--transition);cursor:pointer}');
ap('.gallery-dot.active{background:white;width:18px;border-radius:3px}');
ap('.gallery-thumbs{display:flex;gap:4px;padding:8px;background:rgba(0,0,0,.3);overflow-x:auto}');
ap('.gallery-thumb{width:56px;height:42px;border-radius:6px;overflow:hidden;border:2px solid transparent;cursor:pointer;transition:var(--transition);flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:10px;color:rgba(255,255,255,.7);background:rgba(255,255,255,.1)}');
ap('.gallery-thumb.active{border-color:var(--rose-light)}');
ap('.modal-content{padding:24px 28px}');
ap('.modal-proc-tags{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}');
ap('.modal-title{font-size:20px;font-weight:700;color:var(--charcoal);line-height:1.4;margin-bottom:14px}');
ap('.modal-author-row{display:flex;align-items:center;gap:10px;margin-bottom:16px;padding-bottom:16px;border-bottom:1px solid var(--border-soft)}');
ap('.modal-avatar{width:38px;height:38px;border-radius:50%;background:linear-gradient(135deg,var(--gold-light),var(--rose-light));display:flex;align-items:center;justify-content:center;font-size:16px;border:2px solid var(--border)}');
ap('.modal-author-info{flex:1}');
ap('.modal-author-name{font-size:13.5px;font-weight:700;color:var(--charcoal);margin-bottom:2px}');
ap('.modal-author-meta{font-size:11.5px;color:var(--muted-light);display:flex;align-items:center;gap:8px}');
ap('.modal-body-text{font-size:14px;line-height:1.8;color:var(--ink);margin-bottom:20px}');
ap('.modal-body-text p{margin-bottom:12px}');
ap('.modal-body-text strong{color:var(--charcoal);font-weight:700}');
ap('.info-table{background:var(--ivory);border-radius:var(--radius-sm);padding:14px 16px;margin-bottom:20px;display:grid;grid-template-columns:1fr 1fr;gap:10px 20px}');
ap('.info-row{display:flex;flex-direction:column;gap:2px}');
ap('.info-label{font-size:10.5px;font-weight:700;color:var(--muted-light);letter-spacing:.5px;text-transform:uppercase}');
ap('.info-value{font-size:13px;font-weight:600;color:var(--charcoal)}');
ap('.modal-actions{display:flex;align-items:center;gap:10px;padding:16px 0;border-top:1px solid var(--border-soft);border-bottom:1px solid var(--border-soft);margin-bottom:24px;flex-wrap:wrap}');
ap('.modal-action-btn{display:flex;align-items:center;gap:6px;height:38px;padding:0 16px;border-radius:19px;font-size:13px;font-weight:600;transition:var(--transition);border:1.5px solid var(--border);color:var(--muted);background:var(--white)}');
ap('.modal-action-btn:hover{border-color:var(--rose-mid);color:var(--rose-deep)}');
ap('.modal-action-btn.primary{background:var(--rose-deep);border-color:var(--rose-deep);color:white}');
ap('.modal-action-btn.primary:hover{background:var(--rose-mid);box-shadow:0 4px 12px rgba(196,82,106,.3)}');
ap('.modal-action-btn.liked{background:var(--rose-pale);border-color:var(--rose-light);color:var(--rose-deep)}');
console.log('modal CSS done', fs.statSync('index.html').size);